# Generated by Django 2.0.6 on 2019-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
